### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by VlaoMao** [agalakhov/captdriver#10]
Hello. Driver will not compile, with error log:
`LANG=C make
Making all in src
make[1]: Entering directory '/home/vl/captdriver/src'
gcc -DPACKAGE_NAME=\"captdriver\" -DPACKAGE_TARNAME=\"captdriver\" -DPACKAGE_VERSION=\"0.1.0\" -DPACKAGE_STRING=\"captdriver\ 0.1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"captdriver\" -DVERSION=\"0.1.0\" -I.    -std=c99 -Wall -Wextra -pedantic  -g -O2 -MT prn_lbp2900.o -MD -MP -MF .deps/prn_lbp2900.Tpo -c -o prn_lbp2900.o prn_lbp2900.c

prn_lbp2900.c: In function 'lbp3000_job_prologue':

prn_lbp2900.c:139:2: error: too few arguments to function 'send_job_start'

prn_lbp2900.c:58:13: note: declared here

 static void send_job_start(uint8_t fg, uint16_t page)

Makefile:356: recipe for target 'prn_lbp2900.o' failed

make[1]: *** [prn_lbp2900.o] Error 1

make[1]: Leaving directory '/home/vl/captdriver/src'

Makefile:332: recipe for target 'all-recursive' failed

make: *** [all-recursive] Error 1`

Steps to reproduce:

git clone https://github.com/agalakhov/captdriver.git && cd captdriver
autoreconf -fi
./configure --prefix=/usr
make

**Comment by agalakhov** [comment]
Thank you. The bug is fixed now.
