### ISSUE TITLE
Split the driver and filter into separate binaries? (suggestion)

### ISSUE THREAD

**Issue by mounaiban** [agalakhov/captdriver#21]
Correct me if I am wrong, but is `rastertocapt` both a CUPS filter and driver?

If this is so, would it be beneficial to have separate driver and filter binaries, like a `rastertocapt` filter that only handles conversion to the CAPT format, and a `captdriver` driver that controls the printer (e.g. start a new job) and reads its status (e.g. ink levels, out of paper, etc...)

I was thinking about how this might make debugging and maintenance easier.

This is just a suggestion, and might be a long-term goal, knowing how much work refactoring can be.

**Comment by agalakhov** [comment]
Unfortunately I had to combine them due to extreme weirdness of the CAPT protocol. This is the only printer I'm aware of that uses bidirectional communication all the time.
