### ISSUE TITLE
Low print quality/blurry text compared to Windows

### ISSUE THREAD

**Issue by DigitalKaiser** [agalakhov/captdriver#35]
I am using an LBP2900B printer. When printing the same document using captdriver or from Windows, the resulting page from captdriver has a lesser print quality:

- The text appears blurry/pixelated
- Pictures are not as good as on Windows
- Very thin dotted lines are blurry or are missing some dots

**Comment by agalakhov** [comment]
Check your PPD file and CUPS settings. What you're describing lies outside of captdriver. The quality is lost at the preprocessing stage while generating the raster. Looks like for some reason the page render goes with low resolution and is then upscaled.

The captdriver itself never scales or renders any images. It always works on native printer resolution.

**Comment by DigitalKaiser** [comment]
I using using the PPD from the repo. The only resolution setting I am offered though CUPS is 600 dpi.

According to Canon, the LBP2900B can do "up to 2400 dpi with Automatic Image Reﬁnement". I am not sure if this is related or not.

**Comment by agalakhov** [comment]
The hardware uninterpolated resolution of the printer is 600 DPI. The "2400 DPI" is software-interpolated only.

I'm quite sure there is something that interferes with normal CUPS rasterizing. Which software do you print from?

**Comment by DigitalKaiser** [comment]
You are right, it seems that Firefox/pdf.js on Linux produces bad prints, but with another PDF-viewer it works fine.
